// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using timer_2.Data;

#nullable disable

namespace timer_2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250224022339_tblcreation")]
    partial class tblcreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("timer_2.Models.User", b =>
                {
                    b.Property<int>("fldslno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fldslno"));

                    b.Property<string>("fldmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fldname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fldpassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fldslno");

                    b.ToTable("tblUser");
                });
#pragma warning restore 612, 618
        }
    }
}
